name: spoco

channels:
  - pytorch
  - conda-forge

dependencies:
  - python
  - pytorch
  - torchvision
  - tensorboard
  - h5py
  - scipy
  - scikit-image
  - scikit-learn
  - pyyaml
  - hdbscan
  - pytest
